// Generated by Framer (b5638f1)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    XZGwXHDdq: {
        hover: true
    }
};
const cycleOrder = ["XZGwXHDdq", "zyKK9OBnd"];
const serializationHash = "framer-zMdzc";
const variantClassNames = {
    XZGwXHDdq: "framer-v-1lfgxol",
    zyKK9OBnd: "framer-v-1lemrnm"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Variant 1": "XZGwXHDdq",
    "Variant 2": "zyKK9OBnd"
};
const getProps = ({
    click,
    height,
    id,
    link,
    title,
    width,
    ...props
}) => {
    return { ...props,
        Cdug9kvRd: click ? ? props.Cdug9kvRd,
        DvLJMxTXt: title ? ? props.DvLJMxTXt ? ? "home",
        NnddK2miS: link ? ? props.NnddK2miS,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "XZGwXHDdq"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        DvLJMxTXt,
        NnddK2miS,
        Cdug9kvRd,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "XZGwXHDdq",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTappb0z5e = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (Cdug9kvRd) {
            const res = await Cdug9kvRd(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (gestureVariant === "XZGwXHDdq-hover") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: NnddK2miS,
                    motionChild: true,
                    nodeId: "XZGwXHDdq",
                    scopeId: "hDDj3o6Pp",
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1lfgxol",className,classNames)} framer-1edjfjb`,
                        "data-framer-name": "Variant 1",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "XZGwXHDdq",
                        onTap: onTappb0z5e,
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "XZGwXHDdq-hover": {
                                "data-framer-name": undefined
                            },
                            zyKK9OBnd: {
                                "data-framer-name": "Variant 2"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-msadyk",
                            layoutDependency: layoutDependency,
                            layoutId: "WD3Qy2FT3",
                            children: [isDisplayed() && /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-11txwi6",
                                layoutDependency: layoutDependency,
                                layoutId: "vl0dUdenk",
                                style: {
                                    backgroundColor: "rgb(255, 255, 255)",
                                    borderBottomLeftRadius: 13,
                                    borderBottomRightRadius: 13,
                                    borderTopLeftRadius: 13,
                                    borderTopRightRadius: 13
                                }
                            }), /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "Qkk7dW5kZWZpbmVkL21lZGl1bS92MA==",
                                            "--framer-font-family": '"undefined", monospace',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-text-alignment": "left",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                            "--framer-text-transform": "uppercase"
                                        },
                                        children: "home"
                                    })
                                }),
                                className: "framer-jqf6y3",
                                fonts: ["BI;undefined/medium/v0"],
                                layoutDependency: layoutDependency,
                                layoutId: "wdpAHhroB",
                                style: {
                                    "--extracted-r6o4lv": "rgb(255, 255, 255)",
                                    "--framer-link-text-color": "rgb(0, 153, 255)",
                                    "--framer-link-text-decoration": "underline",
                                    "--framer-paragraph-spacing": "0px"
                                },
                                text: DvLJMxTXt,
                                verticalAlignment: "top",
                                withExternalLayout: true,
                                ...addPropertyOverrides({
                                    zyKK9OBnd: {
                                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                                            children: /*#__PURE__*/ _jsx(motion.p, {
                                                style: {
                                                    "--font-selector": "Qkk7dW5kZWZpbmVkL21lZGl1bS92MA==",
                                                    "--framer-font-family": '"undefined", monospace',
                                                    "--framer-font-size": "18px",
                                                    "--framer-font-weight": "500",
                                                    "--framer-text-alignment": "left",
                                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                                    "--framer-text-transform": "uppercase"
                                                },
                                                children: "home"
                                            })
                                        })
                                    }
                                }, baseVariant, gestureVariant)
                            })]
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-zMdzc.framer-1edjfjb, .framer-zMdzc .framer-1edjfjb { display: block; }", ".framer-zMdzc.framer-1lfgxol { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-zMdzc .framer-msadyk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 1px; height: min-content; justify-content: center; overflow: visible; padding: 0px 4px 0px 4px; position: relative; width: min-content; }", ".framer-zMdzc .framer-11txwi6 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 4px); overflow: hidden; position: relative; width: 4px; will-change: var(--framer-will-change-override, transform); }", ".framer-zMdzc .framer-jqf6y3 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-zMdzc.framer-1lfgxol, .framer-zMdzc .framer-msadyk { gap: 0px; } .framer-zMdzc.framer-1lfgxol > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-zMdzc.framer-1lfgxol > :first-child { margin-left: 0px; } .framer-zMdzc.framer-1lfgxol > :last-child { margin-right: 0px; } .framer-zMdzc .framer-msadyk > * { margin: 0px; margin-bottom: calc(1px / 2); margin-top: calc(1px / 2); } .framer-zMdzc .framer-msadyk > :first-child { margin-top: 0px; } .framer-zMdzc .framer-msadyk > :last-child { margin-bottom: 0px; } }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 17
 * @framerIntrinsicWidth 41.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"zyKK9OBnd":{"layout":["auto","auto"]},"QXsq6H1CG":{"layout":["auto","auto"]}}}
 * @framerVariables {"DvLJMxTXt":"title","NnddK2miS":"link","Cdug9kvRd":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerhDDj3o6Pp = withCSS(Component, css, "framer-zMdzc");
export default FramerhDDj3o6Pp;
FramerhDDj3o6Pp.displayName = "Nav_tab";
FramerhDDj3o6Pp.defaultProps = {
    height: 17,
    width: 41.5
};
addPropertyControls(FramerhDDj3o6Pp, {
    variant: {
        options: ["XZGwXHDdq", "zyKK9OBnd"],
        optionTitles: ["Variant 1", "Variant 2"],
        title: "Variant",
        type: ControlType.Enum
    },
    DvLJMxTXt: {
        defaultValue: "home",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    NnddK2miS: {
        title: "Link",
        type: ControlType.Link
    },
    Cdug9kvRd: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerhDDj3o6Pp, [{
    explicitInter: true,
    fonts: [{
        family: "undefined",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/tqiZMWWRtRr0QZo2zvUKP6F0Crg.woff2",
        weight: "500"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerhDDj3o6Pp",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerVariables": "{\"DvLJMxTXt\":\"title\",\"NnddK2miS\":\"link\",\"Cdug9kvRd\":\"click\"}",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "17",
                "framerIntrinsicWidth": "41.5",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"zyKK9OBnd\":{\"layout\":[\"auto\",\"auto\"]},\"QXsq6H1CG\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerColorSyntax": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./hDDj3o6Pp.map