// Generated by Framer (808fccf)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    getLoadingLazyAtYPosition,
    Image,
    RichText,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/zmEYC9iD1UOT54cJMEp6/GbPwJiOG8vxxWNEyL3cX/aB8W1_bGo.js";
import * as sharedStyle from "https://framerusercontent.com/modules/mj1ycdqgYlGuF0ksVLF0/O3SgnYqp27zxHk0X76Qn/yapCj9upi.js";
import Button from "https://framerusercontent.com/modules/vF96XgfcQIUvJsDKCGE9/en1t0i5XkxSesKP9sns9/HSeVcgIo4.js";
const ButtonFonts = getFonts(Button);
const enabledGestures = {
    ehcnbv7R5: {
        hover: true
    }
};
const cycleOrder = ["ehcnbv7R5", "Cv63P9SU4"];
const serializationHash = "framer-l1hjg";
const variantClassNames = {
    Cv63P9SU4: "framer-v-161bz03",
    ehcnbv7R5: "framer-v-12sa55r"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: 1,
    type: "spring"
};
const animation = {
    filter: "blur(10px)",
    opacity: .001,
    rotate: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 10
};
const transition2 = {
    bounce: 0,
    delay: .05,
    duration: 1.2,
    type: "spring"
};
const textEffect = {
    effect: animation,
    tokenization: "character",
    transition: transition2,
    trigger: "onMount",
    type: "appear"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Variant 1": "ehcnbv7R5",
    "Variant 2 - Without Hover": "Cv63P9SU4"
};
const getProps = ({
    category,
    height,
    id,
    image,
    link,
    title,
    width,
    ...props
}) => {
    return { ...props,
        JAMMo9P72: image ? ? props.JAMMo9P72,
        QLQQo68If: category ? ? props.QLQQo68If ? ? "Branding",
        SyUVB5E6O: link ? ? props.SyUVB5E6O,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "ehcnbv7R5",
        zDao89Fkr: title ? ? props.zDao89Fkr ? ? "Polestar"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        zDao89Fkr,
        JAMMo9P72,
        QLQQo68If,
        SyUVB5E6O,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "ehcnbv7R5",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1rh6wv9 = activeVariantCallback(async (...args) => {
        setVariant("ehcnbv7R5");
    });
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "Cv63P9SU4") return false;
        return true;
    };
    const isDisplayed1 = () => {
        if (gestureVariant === "ehcnbv7R5-hover") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Image, { ...restProps,
                    ...gestureHandlers,
                    background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(componentViewport ? .y || 0),
                        sizes: componentViewport ? .width || "100vw",
                        ...toResponsiveImage(JAMMo9P72)
                    },
                    className: cx(scopingClassNames, "framer-12sa55r", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "ehcnbv7R5",
                    ref: refBinding,
                    style: {
                        borderBottomLeftRadius: 100,
                        borderBottomRightRadius: 100,
                        borderTopLeftRadius: 100,
                        borderTopRightRadius: 100,
                        ...style
                    },
                    ...addPropertyOverrides({
                        "ehcnbv7R5-hover": {
                            "data-framer-name": undefined
                        },
                        Cv63P9SU4: {
                            "data-framer-name": "Variant 2 - Without Hover"
                        }
                    }, baseVariant, gestureVariant),
                    children: isDisplayed() && /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1pdwzkg",
                        layoutDependency: layoutDependency,
                        layoutId: "MCXzD0HPn",
                        style: {
                            backdropFilter: "blur(44px)",
                            backgroundColor: "rgba(0, 0, 0, 0.24)",
                            borderBottomLeftRadius: 72,
                            borderBottomRightRadius: 72,
                            borderTopLeftRadius: 72,
                            borderTopRightRadius: 72,
                            WebkitBackdropFilter: "blur(44px)"
                        },
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                    className: "framer-styles-preset-1tp2un9",
                                    "data-styles-preset": "yapCj9upi",
                                    style: {
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-1of0zx5, var(--token-b9a38ae6-6808-421e-8c6e-e2c5bc817a9d, rgb(255, 255, 255)))"
                                    },
                                    children: "Polestar"
                                })
                            }),
                            className: "framer-5oug7w",
                            "data-highlight": true,
                            effect: textEffect,
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "pqhlsANrZ",
                            onTap: onTap1rh6wv9,
                            style: {
                                "--extracted-1of0zx5": "var(--token-b9a38ae6-6808-421e-8c6e-e2c5bc817a9d, rgb(255, 255, 255))",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: zDao89Fkr,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h5, {
                                    className: "framer-styles-preset-f15uo",
                                    "data-styles-preset": "aB8W1_bGo",
                                    style: {
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-1lwpl3i, var(--token-b9a38ae6-6808-421e-8c6e-e2c5bc817a9d, rgb(255, 255, 255)))"
                                    },
                                    children: "Branding"
                                })
                            }),
                            className: "framer-1l73ez7",
                            effect: textEffect,
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "HATGfa1W_",
                            style: {
                                "--extracted-1lwpl3i": "var(--token-b9a38ae6-6808-421e-8c6e-e2c5bc817a9d, rgb(255, 255, 255))",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: QLQQo68If,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), isDisplayed1() && /*#__PURE__*/ _jsx(ComponentViewportProvider, { ...addPropertyOverrides({
                                "ehcnbv7R5-hover": {
                                    height: 49,
                                    y: (componentViewport ? .y || 0) + 32 + (((componentViewport ? .height || 800) - 64 - 357) / 2 + 0 + 0) + 32 + 174
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-etpqrr-container",
                                layoutDependency: layoutDependency,
                                layoutId: "tUBjQdaDE-container",
                                nodeId: "tUBjQdaDE",
                                rendersWithMotion: true,
                                scopeId: "lbd_lQlxO",
                                children: /*#__PURE__*/ _jsx(Button, {
                                    EYMMXEPet: "Explore More",
                                    height: "100%",
                                    id: "tUBjQdaDE",
                                    layoutId: "tUBjQdaDE",
                                    variant: "nBnQ8BXAI",
                                    width: "100%",
                                    Yi7wepiGi: SyUVB5E6O
                                })
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-l1hjg.framer-19y0l47, .framer-l1hjg .framer-19y0l47 { display: block; }", ".framer-l1hjg.framer-12sa55r { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 463px; height: 800px; justify-content: center; overflow: hidden; padding: 32px 44px 32px 44px; position: relative; width: 480px; will-change: var(--framer-will-change-override, transform); }", ".framer-l1hjg .framer-1pdwzkg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 357px; justify-content: center; max-width: 364px; overflow: visible; padding: 32px; position: relative; width: 100%; }", ".framer-l1hjg .framer-5oug7w { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }", ".framer-l1hjg .framer-1l73ez7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }", ".framer-l1hjg .framer-etpqrr-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-l1hjg.framer-v-161bz03.framer-12sa55r { cursor: unset; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 800
 * @framerIntrinsicWidth 480
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Cv63P9SU4":{"layout":["fixed","fixed"]},"SJdaDFSNa":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"zDao89Fkr":"title","JAMMo9P72":"image","QLQQo68If":"category","SyUVB5E6O":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerlbd_lQlxO = withCSS(Component, css, "framer-l1hjg");
export default Framerlbd_lQlxO;
Framerlbd_lQlxO.displayName = "Card";
Framerlbd_lQlxO.defaultProps = {
    height: 800,
    width: 480
};
addPropertyControls(Framerlbd_lQlxO, {
    variant: {
        options: ["ehcnbv7R5", "Cv63P9SU4"],
        optionTitles: ["Variant 1", "Variant 2 - Without Hover"],
        title: "Variant",
        type: ControlType.Enum
    },
    zDao89Fkr: {
        defaultValue: "Polestar",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    JAMMo9P72: {
        title: "Image",
        type: ControlType.ResponsiveImage
    },
    QLQQo68If: {
        defaultValue: "Branding",
        displayTextArea: false,
        title: "Category",
        type: ControlType.String
    },
    SyUVB5E6O: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(Framerlbd_lQlxO, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...ButtonFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Framerlbd_lQlxO",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "480",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "800",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"Cv63P9SU4\":{\"layout\":[\"fixed\",\"fixed\"]},\"SJdaDFSNa\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"zDao89Fkr\":\"title\",\"JAMMo9P72\":\"image\",\"QLQQo68If\":\"category\",\"SyUVB5E6O\":\"link\"}",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./lbd_lQlxO.map