// Generated by Framer (ab692b1)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/uQabJxc7NQG4uAJhYI1e/cV3khLf796E2gYWbAaxL/wvyy7PS0Y.js";
const cycleOrder = ["oJf_EHaDq", "ooTlbGdR8", "ud2HMxp0m", "aEefvNPgr"];
const serializationHash = "framer-1g5Oh";
const variantClassNames = {
    aEefvNPgr: "framer-v-r8o22h",
    oJf_EHaDq: "framer-v-kemslg",
    ooTlbGdR8: "framer-v-35dcj1",
    ud2HMxp0m: "framer-v-6zrbtd"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    duration: 0,
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "1": "oJf_EHaDq",
    "2": "ooTlbGdR8",
    "3": "ud2HMxp0m",
    "4": "aEefvNPgr"
};
const getProps = ({
    height,
    id,
    label1,
    label2,
    label3,
    label4,
    width,
    ...props
}) => {
    return { ...props,
        HvfJHbU33: label2 ? ? props.HvfJHbU33 ? ? "Web Design",
        pwuah1x3V: label3 ? ? props.pwuah1x3V ? ? "Branding",
        s8uq9o_PT: label4 ? ? props.s8uq9o_PT ? ? "UI/UX",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "oJf_EHaDq",
        Zb96rmzbq: label1 ? ? props.Zb96rmzbq ? ? "Strategy"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Zb96rmzbq,
        HvfJHbU33,
        pwuah1x3V,
        s8uq9o_PT,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "oJf_EHaDq",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-kemslg", className, classNames),
                    "data-framer-name": "1",
                    layoutDependency: layoutDependency,
                    layoutId: "oJf_EHaDq",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 100,
                        borderBottomRightRadius: 100,
                        borderTopLeftRadius: 100,
                        borderTopRightRadius: 100,
                        ...style
                    },
                    ...addPropertyOverrides({
                        aEefvNPgr: {
                            "data-framer-name": "4"
                        },
                        ooTlbGdR8: {
                            "data-framer-name": "2"
                        },
                        ud2HMxp0m: {
                            "data-framer-name": "3"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h6, {
                                className: "framer-styles-preset-yx8cpv",
                                "data-styles-preset": "wvyy7PS0Y",
                                children: "01"
                            })
                        }),
                        className: "framer-wcqigb",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "oBROL14Ly",
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            aEefvNPgr: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.h6, {
                                        className: "framer-styles-preset-yx8cpv",
                                        "data-styles-preset": "wvyy7PS0Y",
                                        children: "04"
                                    })
                                })
                            },
                            ooTlbGdR8: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.h6, {
                                        className: "framer-styles-preset-yx8cpv",
                                        "data-styles-preset": "wvyy7PS0Y",
                                        children: "02"
                                    })
                                })
                            },
                            ud2HMxp0m: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.h6, {
                                        className: "framer-styles-preset-yx8cpv",
                                        "data-styles-preset": "wvyy7PS0Y",
                                        children: "03"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h6, {
                                className: "framer-styles-preset-yx8cpv",
                                "data-styles-preset": "wvyy7PS0Y",
                                children: "Strategy"
                            })
                        }),
                        className: "framer-19rcwc0",
                        "data-framer-name": "text",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "vF8gGJ891",
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: Zb96rmzbq,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            aEefvNPgr: {
                                text: s8uq9o_PT
                            },
                            ooTlbGdR8: {
                                text: HvfJHbU33
                            },
                            ud2HMxp0m: {
                                text: pwuah1x3V
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-1g5Oh.framer-14s44al, .framer-1g5Oh .framer-14s44al { display: block; }", ".framer-1g5Oh.framer-kemslg { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 36px; justify-content: center; overflow: hidden; padding: 14px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-1g5Oh .framer-wcqigb, .framer-1g5Oh .framer-19rcwc0 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-1g5Oh.framer-kemslg { gap: 0px; } .framer-1g5Oh.framer-kemslg > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-1g5Oh.framer-kemslg > :first-child { margin-left: 0px; } .framer-1g5Oh.framer-kemslg > :last-child { margin-right: 0px; } }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 36
 * @framerIntrinsicWidth 98.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"ooTlbGdR8":{"layout":["auto","fixed"]},"ud2HMxp0m":{"layout":["auto","fixed"]},"aEefvNPgr":{"layout":["auto","fixed"]}}}
 * @framerVariables {"Zb96rmzbq":"label1","HvfJHbU33":"label2","pwuah1x3V":"label3","s8uq9o_PT":"label4"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerS0QfV3zi0 = withCSS(Component, css, "framer-1g5Oh");
export default FramerS0QfV3zi0;
FramerS0QfV3zi0.displayName = "Pill";
FramerS0QfV3zi0.defaultProps = {
    height: 36,
    width: 98.5
};
addPropertyControls(FramerS0QfV3zi0, {
    variant: {
        options: ["oJf_EHaDq", "ooTlbGdR8", "ud2HMxp0m", "aEefvNPgr"],
        optionTitles: ["1", "2", "3", "4"],
        title: "Variant",
        type: ControlType.Enum
    },
    Zb96rmzbq: {
        defaultValue: "Strategy",
        displayTextArea: false,
        title: "Label 1",
        type: ControlType.String
    },
    HvfJHbU33: {
        defaultValue: "Web Design",
        displayTextArea: false,
        title: "Label 2",
        type: ControlType.String
    },
    pwuah1x3V: {
        defaultValue: "Branding",
        displayTextArea: false,
        title: "Label 3",
        type: ControlType.String
    },
    s8uq9o_PT: {
        defaultValue: "UI/UX",
        displayTextArea: false,
        title: "Label 4",
        type: ControlType.String
    }
});
addFonts(FramerS0QfV3zi0, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerS0QfV3zi0",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"Zb96rmzbq\":\"label1\",\"HvfJHbU33\":\"label2\",\"pwuah1x3V\":\"label3\",\"s8uq9o_PT\":\"label4\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"ooTlbGdR8\":{\"layout\":[\"auto\",\"fixed\"]},\"ud2HMxp0m\":{\"layout\":[\"auto\",\"fixed\"]},\"aEefvNPgr\":{\"layout\":[\"auto\",\"fixed\"]}}}",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "36",
                "framerIntrinsicWidth": "98.5",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}