// Generated by Framer (9d598a4)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["BI;undefined/medium/v0"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "undefined",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/tqiZMWWRtRr0QZo2zvUKP6F0Crg.woff2",
        weight: "500"
    }]
}];
export const css = [".framer-nWjvN .framer-styles-preset-g92w1w:not(.rich-text-wrapper), .framer-nWjvN .framer-styles-preset-g92w1w.rich-text-wrapper h5 { --framer-font-family: \"undefined\", monospace; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.04em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }"];
export const className = "framer-nWjvN";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}