// Generated by Framer (f712822)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["BI;Apfel Grotezk/Regular/v0"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "Apfel Grotezk",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/KwK0fH9Qx1gAi2nY6HV637MnF0.woff2",
        weight: "400"
    }]
}];
export const css = [".framer-15jtr .framer-styles-preset-6nz3az:not(.rich-text-wrapper), .framer-15jtr .framer-styles-preset-6nz3az.rich-text-wrapper p { --framer-font-family: \"Apfel Grotezk\", \"Apfel Grotezk Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0.01em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-61969a04-61ec-49b7-8fb6-050c58691dcd, #707070); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }"];
export const className = "framer-15jtr";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}