// Generated by Framer (808fccf)
import siteMetadata from "https://framerusercontent.com/modules/bqvWRMS4UZHjO10hTyD9/wX22ADCEGm0eOAZoXRfJ/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "1w7mlkg",
            mediaQuery: "(min-width: 1440px)"
        }, {
            hash: "ezadf",
            mediaQuery: "(min-width: 810px) and (max-width: 1439.98px)"
        }, {
            hash: "7v4wrl",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {},
        robots: "max-image-preview:large",
        serializationId: "framer-pOhgF",
        title: siteMetadata(params, activeLocale).title || "Projects",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}