// Generated by Framer (2abc263)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    znl5vOW2u: {
        hover: true
    }
};
const cycleOrder = ["znl5vOW2u", "pz3SheFAW"];
const serializationHash = "framer-9VN4e";
const variantClassNames = {
    pz3SheFAW: "framer-v-ltl5kb",
    znl5vOW2u: "framer-v-x7bt5z"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: 1,
    type: "spring"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Variant 1": "znl5vOW2u",
    "Variant 2": "pz3SheFAW"
};
const getProps = ({
    description,
    height,
    id,
    image2,
    width,
    ...props
}) => {
    return { ...props,
        HHjSLvjob: image2 ? ? props.HHjSLvjob,
        nxWgFxbbL: description ? ? props.nxWgFxbbL ? ? "We collaborate with industry leaders, innovative startups, and global enterprises to deliver exceptional solutions. Our clients trust us to bring their vision to life with precision, creativity, and expertise.",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "znl5vOW2u"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        nxWgFxbbL,
        HHjSLvjob,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "znl5vOW2u",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (gestureVariant === "znl5vOW2u-hover") return true;
        return false;
    };
    const isDisplayed1 = () => {
        if (baseVariant === "pz3SheFAW") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-x7bt5z", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "znl5vOW2u",
                    ref: refBinding,
                    style: {
                        backdropFilter: "blur(44px)",
                        backgroundColor: "var(--token-17dd74c0-48e7-4cc6-8876-ee446770c16e, rgb(242, 242, 242))",
                        borderBottomLeftRadius: 72,
                        borderBottomRightRadius: 72,
                        borderTopLeftRadius: 72,
                        borderTopRightRadius: 72,
                        WebkitBackdropFilter: "blur(44px)",
                        ...style
                    },
                    ...addPropertyOverrides({
                        "znl5vOW2u-hover": {
                            "data-framer-name": undefined
                        },
                        pz3SheFAW: {
                            "data-framer-name": "Variant 2"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(Image, {
                        background: {
                            alt: "",
                            fit: "fit",
                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + 44 + (((componentViewport ? .height || 357) - 88 - 86) / 2 + 0 + 0)),
                            sizes: "197px",
                            ...toResponsiveImage(HHjSLvjob),
                            ...{
                                positionX: "center",
                                positionY: "center"
                            }
                        },
                        className: "framer-hi8j2x",
                        "data-framer-name": "Brand_logo",
                        layoutDependency: layoutDependency,
                        layoutId: "Tkvp9p9SV",
                        ...addPropertyOverrides({
                            "znl5vOW2u-hover": {
                                background: {
                                    alt: "",
                                    fit: "fit",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + 44 + (((componentViewport ? .height || 357) - 88 - 214) / 2 + 0 + 0)),
                                    sizes: "197px",
                                    ...toResponsiveImage(HHjSLvjob),
                                    ...{
                                        positionX: "center",
                                        positionY: "center"
                                    }
                                }
                            },
                            pz3SheFAW: {
                                background: {
                                    alt: "",
                                    fit: "fit",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + 44 + (((componentViewport ? .height || 357) - 88 - 194) / 2 + 0 + 0)),
                                    sizes: "197px",
                                    ...toResponsiveImage(HHjSLvjob),
                                    ...{
                                        positionX: "center",
                                        positionY: "center"
                                    }
                                }
                            }
                        }, baseVariant, gestureVariant)
                    }), isDisplayed() && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "Q1VTVE9NO05ldWUgTW9udHJlYWwgUmVndWxhcg==",
                                    "--framer-font-family": '"Neue Montreal Regular", "Neue Montreal Regular Placeholder", sans-serif',
                                    "--framer-font-size": "14px",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-a099af4a-6aec-40a3-976c-256397b32f03, rgb(22, 22, 22)))",
                                    "--framer-text-transform": "inherit"
                                },
                                children: "We collaborate with industry leaders, innovative startups, and global enterprises to deliver exceptional solutions. Our clients trust us to bring their vision to life with precision, creativity, and expertise."
                            })
                        }),
                        className: "framer-kdkz5b",
                        fonts: ["CUSTOM;Neue Montreal Regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "A2Emo4z47",
                        style: {
                            "--extracted-r6o4lv": "var(--token-a099af4a-6aec-40a3-976c-256397b32f03, rgb(22, 22, 22))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: nxWgFxbbL,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), isDisplayed1() && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "Q1VTVE9NO05ldWUgTW9udHJlYWwgUmVndWxhcg==",
                                    "--framer-font-family": '"Neue Montreal Regular", "Neue Montreal Regular Placeholder", sans-serif',
                                    "--framer-font-size": "14px",
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-a099af4a-6aec-40a3-976c-256397b32f03, rgb(22, 22, 22)))",
                                    "--framer-text-transform": "inherit"
                                },
                                children: "We collaborate with industry leaders, innovative startups, and global enterprises to deliver exceptional solutions. Our clients trust us to bring their vision to life with precision, creativity, and expertise."
                            })
                        }),
                        className: "framer-15c664e",
                        fonts: ["CUSTOM;Neue Montreal Regular"],
                        layoutDependency: layoutDependency,
                        layoutId: "xxe1m__rh",
                        style: {
                            "--extracted-r6o4lv": "var(--token-a099af4a-6aec-40a3-976c-256397b32f03, rgb(22, 22, 22))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: nxWgFxbbL,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-9VN4e.framer-1q28l1t, .framer-9VN4e .framer-1q28l1t { display: block; }", ".framer-9VN4e.framer-x7bt5z { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 357px; justify-content: center; overflow: visible; padding: 44px; position: relative; width: 366px; }", ".framer-9VN4e .framer-hi8j2x { flex: none; height: 86px; overflow: visible; position: relative; width: 197px; }", ".framer-9VN4e .framer-kdkz5b, .framer-9VN4e .framer-15c664e { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-9VN4e.framer-x7bt5z { gap: 0px; } .framer-9VN4e.framer-x7bt5z > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-9VN4e.framer-x7bt5z > :first-child { margin-top: 0px; } .framer-9VN4e.framer-x7bt5z > :last-child { margin-bottom: 0px; } }", ".framer-9VN4e.framer-v-ltl5kb.framer-x7bt5z { cursor: unset; }", ".framer-9VN4e.framer-v-x7bt5z.hover.framer-x7bt5z { gap: 44px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-9VN4e.framer-v-x7bt5z.hover.framer-x7bt5z { gap: 0px; } .framer-9VN4e.framer-v-x7bt5z.hover.framer-x7bt5z > * { margin: 0px; margin-bottom: calc(44px / 2); margin-top: calc(44px / 2); } .framer-9VN4e.framer-v-x7bt5z.hover.framer-x7bt5z > :first-child { margin-top: 0px; } .framer-9VN4e.framer-v-x7bt5z.hover.framer-x7bt5z > :last-child { margin-bottom: 0px; } }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 357
 * @framerIntrinsicWidth 366
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"pz3SheFAW":{"layout":["fixed","fixed"]},"kvQuefz7y":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"nxWgFxbbL":"description","HHjSLvjob":"image2"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerKeE7UEvjS = withCSS(Component, css, "framer-9VN4e");
export default FramerKeE7UEvjS;
FramerKeE7UEvjS.displayName = "client_card";
FramerKeE7UEvjS.defaultProps = {
    height: 357,
    width: 366
};
addPropertyControls(FramerKeE7UEvjS, {
    variant: {
        options: ["znl5vOW2u", "pz3SheFAW"],
        optionTitles: ["Variant 1", "Variant 2"],
        title: "Variant",
        type: ControlType.Enum
    },
    nxWgFxbbL: {
        defaultValue: "We collaborate with industry leaders, innovative startups, and global enterprises to deliver exceptional solutions. Our clients trust us to bring their vision to life with precision, creativity, and expertise.",
        displayTextArea: false,
        title: "Description",
        type: ControlType.String
    },
    HHjSLvjob: {
        title: "Image 2",
        type: ControlType.ResponsiveImage
    }
});
addFonts(FramerKeE7UEvjS, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerKeE7UEvjS",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "357",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"pz3SheFAW\":{\"layout\":[\"fixed\",\"fixed\"]},\"kvQuefz7y\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"nxWgFxbbL\":\"description\",\"HHjSLvjob\":\"image2\"}",
                "framerIntrinsicWidth": "366",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./KeE7UEvjS.map