// Generated by Framer (9f1494d)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = {
    zZExvfcby: {
        hover: true
    }
};
const cycleOrder = ["zZExvfcby", "ExFDv6OlC", "C3wgJF12A", "ix53cAnNC", "O8KcZxr5w"];
const serializationHash = "framer-2Q8zM";
const variantClassNames = {
    C3wgJF12A: "framer-v-kb14wj",
    ExFDv6OlC: "framer-v-6zels",
    ix53cAnNC: "framer-v-xshp1j",
    O8KcZxr5w: "framer-v-150318b",
    zZExvfcby: "framer-v-1juyh6d"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: .2,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const transition2 = {
    delay: 0,
    duration: 1,
    ease: [0, 0, 1, 1],
    type: "tween"
};
const animation = {
    opacity: 1,
    rotate: 360,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Form Button": "zZExvfcby",
    Disabled: "C3wgJF12A",
    Error: "O8KcZxr5w",
    Loading: "ExFDv6OlC",
    Success: "ix53cAnNC"
};
const getProps = ({
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        Ave8rg_Ea: title ? ? props.Ave8rg_Ea ? ? "Submit",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "zZExvfcby"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Ave8rg_Ea,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "zZExvfcby",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "ExFDv6OlC") return false;
        return true;
    };
    const isDisplayed1 = () => {
        if (baseVariant === "ExFDv6OlC") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.button, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1juyh6d", className, classNames),
                    "data-framer-name": "Form Button",
                    "data-reset": "button",
                    layoutDependency: layoutDependency,
                    layoutId: "zZExvfcby",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-0760290c-0963-4afd-8b72-f7c94940d48f, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 20,
                        borderBottomRightRadius: 20,
                        borderTopLeftRadius: 20,
                        borderTopRightRadius: 20,
                        opacity: 1,
                        ...style
                    },
                    variants: {
                        "zZExvfcby-hover": {
                            opacity: 1
                        },
                        C3wgJF12A: {
                            opacity: .5
                        },
                        ix53cAnNC: {
                            opacity: 1
                        },
                        O8KcZxr5w: {
                            backgroundColor: "rgba(255, 34, 68, 0.15)",
                            opacity: 1
                        }
                    },
                    ...addPropertyOverrides({
                        "zZExvfcby-hover": {
                            "data-framer-name": undefined
                        },
                        C3wgJF12A: {
                            "data-framer-name": "Disabled"
                        },
                        ExFDv6OlC: {
                            "data-framer-name": "Loading"
                        },
                        ix53cAnNC: {
                            "data-framer-name": "Success"
                        },
                        O8KcZxr5w: {
                            "data-framer-name": "Error"
                        }
                    }, baseVariant, gestureVariant),
                    children: [isDisplayed() && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "Qkk7dW5kZWZpbmVkL21lZGl1bS92MA==",
                                    "--framer-font-family": '"undefined", monospace',
                                    "--framer-font-size": "14px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "-0.02em",
                                    "--framer-line-height": "1.3em",
                                    "--framer-text-alignment": "left",
                                    "--framer-text-transform": "uppercase"
                                },
                                children: "Submit"
                            })
                        }),
                        className: "framer-13na5k5",
                        fonts: ["BI;undefined/medium/v0"],
                        layoutDependency: layoutDependency,
                        layoutId: "R8gwegd2h",
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                            opacity: 1
                        },
                        text: Ave8rg_Ea,
                        variants: {
                            "zZExvfcby-hover": {
                                opacity: .6
                            },
                            O8KcZxr5w: {
                                "--extracted-r6o4lv": "rgb(255, 38, 38)"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            ix53cAnNC: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "Qkk7dW5kZWZpbmVkL21lZGl1bS92MA==",
                                            "--framer-font-family": '"undefined", monospace',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-letter-spacing": "-0.02em",
                                            "--framer-line-height": "1.3em",
                                            "--framer-text-alignment": "left",
                                            "--framer-text-transform": "uppercase"
                                        },
                                        children: "Thank you"
                                    })
                                }),
                                text: undefined
                            },
                            O8KcZxr5w: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "Qkk7dW5kZWZpbmVkL21lZGl1bS92MA==",
                                            "--framer-font-family": '"undefined", monospace',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-letter-spacing": "-0.02em",
                                            "--framer-line-height": "1.3em",
                                            "--framer-text-alignment": "left",
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 38, 38))"
                                        },
                                        children: "Something went wrong"
                                    })
                                }),
                                text: undefined
                            }
                        }, baseVariant, gestureVariant)
                    }), isDisplayed1() && /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1i7o1ui",
                        "data-framer-name": "Spinner",
                        layoutDependency: layoutDependency,
                        layoutId: "lSWRIRymU",
                        style: {
                            mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                            WebkitMask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add"
                        },
                        children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __framer__loop: animation,
                            __framer__loopEffectEnabled: true,
                            __framer__loopRepeatDelay: 0,
                            __framer__loopRepeatType: "loop",
                            __framer__loopTransition: transition2,
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            className: "framer-oo9ojo",
                            "data-framer-name": "Conic",
                            layoutDependency: layoutDependency,
                            layoutId: "M3d73m1AI",
                            style: {
                                background: "conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(0, 0, 0) 342deg)",
                                mask: "none",
                                WebkitMask: "none"
                            },
                            variants: {
                                ExFDv6OlC: {
                                    mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                                    WebkitMask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-17dye6r",
                                "data-framer-name": "Rounding",
                                layoutDependency: layoutDependency,
                                layoutId: "rtbyjHv4x",
                                style: {
                                    backgroundColor: "rgb(255, 255, 255)",
                                    borderBottomLeftRadius: 1,
                                    borderBottomRightRadius: 1,
                                    borderTopLeftRadius: 1,
                                    borderTopRightRadius: 1
                                },
                                transformTemplate: transformTemplate1
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-2Q8zM.framer-1vqqccx, .framer-2Q8zM .framer-1vqqccx { display: block; }", ".framer-2Q8zM.framer-1juyh6d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 240px; }", ".framer-2Q8zM .framer-13na5k5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-2Q8zM .framer-1i7o1ui { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }", ".framer-2Q8zM .framer-oo9ojo { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }", ".framer-2Q8zM .framer-17dye6r { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-2Q8zM.framer-1juyh6d { gap: 0px; } .framer-2Q8zM.framer-1juyh6d > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-2Q8zM.framer-1juyh6d > :first-child { margin-left: 0px; } .framer-2Q8zM.framer-1juyh6d > :last-child { margin-right: 0px; } }", ".framer-2Q8zM.framer-v-6zels.framer-1juyh6d, .framer-2Q8zM.framer-v-kb14wj.framer-1juyh6d, .framer-2Q8zM.framer-v-xshp1j.framer-1juyh6d, .framer-2Q8zM.framer-v-150318b.framer-1juyh6d { cursor: unset; }", ".framer-2Q8zM.framer-v-6zels .framer-oo9ojo { overflow: hidden; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 240
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"ExFDv6OlC":{"layout":["fixed","fixed"]},"C3wgJF12A":{"layout":["fixed","fixed"]},"ix53cAnNC":{"layout":["fixed","fixed"]},"O8KcZxr5w":{"layout":["fixed","fixed"]},"gbqY1ZwyW":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"Ave8rg_Ea":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerLBrOtvowc = withCSS(Component, css, "framer-2Q8zM");
export default FramerLBrOtvowc;
FramerLBrOtvowc.displayName = "Button Form 2";
FramerLBrOtvowc.defaultProps = {
    height: 40,
    width: 240
};
addPropertyControls(FramerLBrOtvowc, {
    variant: {
        options: ["zZExvfcby", "ExFDv6OlC", "C3wgJF12A", "ix53cAnNC", "O8KcZxr5w"],
        optionTitles: ["Form Button", "Loading", "Disabled", "Success", "Error"],
        title: "Variant",
        type: ControlType.Enum
    },
    Ave8rg_Ea: {
        defaultValue: "Submit",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(FramerLBrOtvowc, [{
    explicitInter: true,
    fonts: [{
        family: "undefined",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/tqiZMWWRtRr0QZo2zvUKP6F0Crg.woff2",
        weight: "500"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerLBrOtvowc",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"ExFDv6OlC\":{\"layout\":[\"fixed\",\"fixed\"]},\"C3wgJF12A\":{\"layout\":[\"fixed\",\"fixed\"]},\"ix53cAnNC\":{\"layout\":[\"fixed\",\"fixed\"]},\"O8KcZxr5w\":{\"layout\":[\"fixed\",\"fixed\"]},\"gbqY1ZwyW\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerContractVersion": "1",
                "framerVariables": "{\"Ave8rg_Ea\":\"title\"}",
                "framerIntrinsicHeight": "40",
                "framerIntrinsicWidth": "240",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./LBrOtvowc.map