// Generated by Framer (808fccf)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["BI;Apfel Grotezk/Regular/v0", "BI;Apfel Grotezk/Regular/v0"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Apfel Grotezk",
        source: "builtIn",
        style: "normal",
        uiFamilyName: "Apfel Grotezk",
        url: "https://framerusercontent.com/assets/KwK0fH9Qx1gAi2nY6HV637MnF0.woff2",
        weight: "400"
    }]
}];
export const css = [".framer-BgVdb .framer-styles-preset-yx8cpv:not(.rich-text-wrapper), .framer-BgVdb .framer-styles-preset-yx8cpv.rich-text-wrapper h6 { --framer-font-family: \"Apfel Grotezk\", \"Apfel Grotezk Placeholder\", sans-serif; --framer-font-family-bold: \"Apfel Grotezk\", \"Apfel Grotezk Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }"];
export const className = "framer-BgVdb";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}