// Generated by Framer (9f1494d)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Material
} from "https://framerusercontent.com/modules/6Ldpz1V0DkD45gXvi67I/PCgBX5d6MdQT7E7nhdXn/Material.js";
const MaterialFonts = getFonts(Material);
const enabledGestures = {
    fmjjA9L0j: {
        hover: true
    },
    nBnQ8BXAI: {
        hover: true
    }
};
const cycleOrder = ["nBnQ8BXAI", "fmjjA9L0j"];
const serializationHash = "framer-yJAKf";
const variantClassNames = {
    fmjjA9L0j: "framer-v-5iwahy",
    nBnQ8BXAI: "framer-v-mmrlrr"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Variant 1": "nBnQ8BXAI",
    "Variant 2": "fmjjA9L0j"
};
const getProps = ({
    click,
    click2,
    click3,
    click4,
    height,
    id,
    link,
    title,
    width,
    ...props
}) => {
    return { ...props,
        bd4E9KyfX: click2 ? ? props.bd4E9KyfX,
        eNtb7rxyF: click3 ? ? props.eNtb7rxyF,
        EYMMXEPet: title ? ? props.EYMMXEPet ? ? "Explore More",
        itLLRZD7G: click4 ? ? props.itLLRZD7G,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "nBnQ8BXAI",
        xopRUZpUT: click ? ? props.xopRUZpUT,
        Yi7wepiGi: link ? ? props.Yi7wepiGi
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        EYMMXEPet,
        Yi7wepiGi,
        xopRUZpUT,
        bd4E9KyfX,
        eNtb7rxyF,
        itLLRZD7G,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "nBnQ8BXAI",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap19arx5g = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (xopRUZpUT) {
            const res = await xopRUZpUT(...args);
            if (res === false) return false;
        }
        if (bd4E9KyfX) {
            const res = await bd4E9KyfX(...args);
            if (res === false) return false;
        }
        if (eNtb7rxyF) {
            const res = await eNtb7rxyF(...args);
            if (res === false) return false;
        }
        if (itLLRZD7G) {
            const res = await itLLRZD7G(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: Yi7wepiGi,
                    motionChild: true,
                    nodeId: "nBnQ8BXAI",
                    scopeId: "HSeVcgIo4",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-mmrlrr",className,classNames)} framer-1eyjkso`,
                        "data-framer-name": "Variant 1",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "nBnQ8BXAI",
                        onTap: onTap19arx5g,
                        ref: refBinding,
                        style: {
                            backdropFilter: "blur(32px)",
                            backgroundColor: "rgba(0, 0, 0, 0.23)",
                            borderBottomLeftRadius: 20,
                            borderBottomRightRadius: 20,
                            borderTopLeftRadius: 20,
                            borderTopRightRadius: 20,
                            WebkitBackdropFilter: "blur(32px)",
                            ...style
                        },
                        variants: {
                            fmjjA9L0j: {
                                backgroundColor: "rgb(255, 255, 255)"
                            }
                        },
                        ...addPropertyOverrides({
                            "fmjjA9L0j-hover": {
                                "data-framer-name": undefined
                            },
                            "nBnQ8BXAI-hover": {
                                "data-framer-name": undefined
                            },
                            fmjjA9L0j: {
                                "data-framer-name": "Variant 2"
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "Q1VTVE9NO05ldWUgTW9udHJlYWwgUmVndWxhcg==",
                                        "--framer-font-family": '"Neue Montreal Regular", "Neue Montreal Regular Placeholder", sans-serif',
                                        "--framer-font-size": "14px",
                                        "--framer-text-alignment": "center",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"
                                    },
                                    children: "Explore More"
                                })
                            }),
                            className: "framer-1iaov7i",
                            fonts: ["CUSTOM;Neue Montreal Regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "jfUJcssXs",
                            style: {
                                "--extracted-r6o4lv": "rgb(255, 255, 255)",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: EYMMXEPet,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                fmjjA9L0j: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "Qkk7dW5kZWZpbmVkL21lZGl1bS92MA==",
                                                "--framer-font-family": '"undefined", monospace',
                                                "--framer-font-size": "14px",
                                                "--framer-font-weight": "500",
                                                "--framer-text-alignment": "center",
                                                "--framer-text-transform": "uppercase"
                                            },
                                            children: "Explore More"
                                        })
                                    }),
                                    fonts: ["BI;undefined/medium/v0"]
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-p8oi1e",
                            layoutDependency: layoutDependency,
                            layoutId: "EuMntxp5X",
                            children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-1u9vmth-container",
                                    isAuthoredByUser: true,
                                    isModuleExternal: true,
                                    layoutDependency: layoutDependency,
                                    layoutId: "xs7n30N6D-container",
                                    nodeId: "xs7n30N6D",
                                    rendersWithMotion: true,
                                    scopeId: "HSeVcgIo4",
                                    style: {
                                        rotate: 0
                                    },
                                    variants: {
                                        "fmjjA9L0j-hover": {
                                            rotate: 90
                                        },
                                        "nBnQ8BXAI-hover": {
                                            rotate: 90
                                        }
                                    },
                                    children: /*#__PURE__*/ _jsx(Material, {
                                        color: "rgb(255, 255, 255)",
                                        height: "100%",
                                        iconSearch: "Home",
                                        iconSelection: "Add",
                                        iconStyle15: "Filled",
                                        iconStyle2: "Filled",
                                        iconStyle7: "Filled",
                                        id: "xs7n30N6D",
                                        layoutId: "xs7n30N6D",
                                        mirrored: false,
                                        selectByList: true,
                                        style: {
                                            height: "100%",
                                            width: "100%"
                                        },
                                        width: "100%",
                                        ...addPropertyOverrides({
                                            fmjjA9L0j: {
                                                color: "rgb(0, 0, 0)"
                                            }
                                        }, baseVariant, gestureVariant)
                                    })
                                })
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-yJAKf.framer-1eyjkso, .framer-yJAKf .framer-1eyjkso { display: block; }", ".framer-yJAKf.framer-mmrlrr { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 16px 24px 16px 24px; position: relative; text-decoration: none; width: min-content; }", ".framer-yJAKf .framer-1iaov7i { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-yJAKf .framer-p8oi1e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-yJAKf .framer-1u9vmth-container { flex: none; height: 12px; position: relative; width: 12px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-yJAKf.framer-mmrlrr, .framer-yJAKf .framer-p8oi1e { gap: 0px; } .framer-yJAKf.framer-mmrlrr > *, .framer-yJAKf .framer-p8oi1e > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-yJAKf.framer-mmrlrr > :first-child, .framer-yJAKf .framer-p8oi1e > :first-child { margin-left: 0px; } .framer-yJAKf.framer-mmrlrr > :last-child, .framer-yJAKf .framer-p8oi1e > :last-child { margin-right: 0px; } }", ".framer-yJAKf.framer-v-5iwahy.framer-mmrlrr { padding: 24px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 49
 * @framerIntrinsicWidth 150
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"fmjjA9L0j":{"layout":["auto","auto"]},"JaaFz9k3f":{"layout":["auto","auto"]},"tlnYlqW43":{"layout":["auto","auto"]}}}
 * @framerVariables {"EYMMXEPet":"title","Yi7wepiGi":"link","xopRUZpUT":"click","bd4E9KyfX":"click2","eNtb7rxyF":"click3","itLLRZD7G":"click4"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerHSeVcgIo4 = withCSS(Component, css, "framer-yJAKf");
export default FramerHSeVcgIo4;
FramerHSeVcgIo4.displayName = "Button";
FramerHSeVcgIo4.defaultProps = {
    height: 49,
    width: 150
};
addPropertyControls(FramerHSeVcgIo4, {
    variant: {
        options: ["nBnQ8BXAI", "fmjjA9L0j"],
        optionTitles: ["Variant 1", "Variant 2"],
        title: "Variant",
        type: ControlType.Enum
    },
    EYMMXEPet: {
        defaultValue: "Explore More",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    Yi7wepiGi: {
        title: "Link",
        type: ControlType.Link
    },
    xopRUZpUT: {
        title: "Click",
        type: ControlType.EventHandler
    },
    bd4E9KyfX: {
        title: "Click 2",
        type: ControlType.EventHandler
    },
    eNtb7rxyF: {
        title: "Click 3",
        type: ControlType.EventHandler
    },
    itLLRZD7G: {
        title: "Click 4",
        type: ControlType.EventHandler
    }
});
addFonts(FramerHSeVcgIo4, [{
    explicitInter: true,
    fonts: [{
        family: "Neue Montreal Regular",
        source: "custom",
        url: "https://framerusercontent.com/assets/EN0wrjjcgDdG3SMgxfEI19PNHRs.woff2"
    }, {
        family: "undefined",
        source: "builtIn",
        style: "normal",
        url: "https://framerusercontent.com/assets/tqiZMWWRtRr0QZo2zvUKP6F0Crg.woff2",
        weight: "500"
    }]
}, ...MaterialFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerHSeVcgIo4",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"fmjjA9L0j\":{\"layout\":[\"auto\",\"auto\"]},\"JaaFz9k3f\":{\"layout\":[\"auto\",\"auto\"]},\"tlnYlqW43\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "49",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "150",
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"EYMMXEPet\":\"title\",\"Yi7wepiGi\":\"link\",\"xopRUZpUT\":\"click\",\"bd4E9KyfX\":\"click2\",\"eNtb7rxyF\":\"click3\",\"itLLRZD7G\":\"click4\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./HSeVcgIo4.map