// Generated by Framer (06534cb)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    SVG,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    MweN1odic: {
        hover: true
    }
};
const serializationHash = "framer-YOy7n";
const variantClassNames = {
    MweN1odic: "framer-v-1cnw714"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    link,
    width,
    ...props
}) => {
    return { ...props,
        WqPBLyoyk: link ? ? props.WqPBLyoyk
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        WqPBLyoyk,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "MweN1odic",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: WqPBLyoyk,
                    motionChild: true,
                    nodeId: "MweN1odic",
                    scopeId: "DK77DvEEr",
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1cnw714",className,classNames)} framer-1cn04ox`,
                        "data-framer-name": "Variant 1",
                        layoutDependency: layoutDependency,
                        layoutId: "MweN1odic",
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "MweN1odic-hover": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-1avy8l0",
                            "data-framer-name": "Vector (14)",
                            layout: "position",
                            layoutDependency: layoutDependency,
                            layoutId: "i5HLFzgbP",
                            opacity: 1,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 115 115"><path d="M 56.784 44.013 C 63.986 43.883 69.882 49.62 70.016 56.744 C 70.153 63.968 64.46 69.862 57.292 70.008 C 50.033 70.156 44.13 64.41 44.02 57.216 C 43.909 49.987 49.645 44.154 56.784 44.013 Z M 57.753 55.816 C 57.734 55.804 57.718 55.795 57.7 55.784 C 57.7 55.615 57.705 55.449 57.7 55.28 C 57.691 54.942 57.554 54.806 57.214 54.803 C 56.622 54.799 56.029 54.799 55.436 54.803 C 55.087 54.806 54.946 54.952 54.946 55.305 L 54.946 63.024 C 54.946 63.368 55.096 63.512 55.447 63.512 C 55.997 63.514 56.549 63.512 57.098 63.512 C 57.575 63.512 57.686 63.402 57.686 62.935 C 57.686 61.64 57.682 60.344 57.686 59.049 C 57.686 58.568 57.794 58.108 58.049 57.693 C 58.38 57.152 58.883 56.979 59.488 57.059 C 60.037 57.129 60.386 57.462 60.516 57.98 C 60.614 58.37 60.659 58.78 60.664 59.182 C 60.682 60.458 60.669 61.738 60.669 63.015 C 60.669 63.368 60.808 63.507 61.159 63.51 C 61.761 63.512 62.36 63.51 62.962 63.51 C 63.343 63.51 63.475 63.375 63.475 62.985 C 63.475 61.562 63.489 60.142 63.466 58.719 C 63.457 58.18 63.409 57.635 63.306 57.106 C 63.085 55.975 62.508 55.113 61.33 54.797 C 60.614 54.605 59.889 54.619 59.171 54.806 C 58.576 54.961 58.108 55.307 57.75 55.809 Z M 50.967 59.145 L 50.967 62.928 C 50.967 63.368 51.106 63.512 51.537 63.512 L 53.163 63.512 C 53.557 63.512 53.712 63.354 53.712 62.953 L 53.712 55.36 C 53.712 54.961 53.56 54.803 53.163 54.801 C 52.629 54.797 52.096 54.801 51.562 54.801 C 51.104 54.801 50.97 54.936 50.97 55.387 L 50.97 59.145 Z M 50.564 52.286 C 50.564 53.269 51.357 54.065 52.333 54.062 C 53.309 54.062 54.109 53.262 54.111 52.286 C 54.116 51.317 53.309 50.51 52.335 50.51 C 51.355 50.51 50.564 51.301 50.564 52.284 Z" fill="rgba(255, 255, 255, 0.44)"></path></svg>',
                            svgContentId: 10935230669,
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                "MweN1odic-hover": {
                                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 115 115"><path d="M 56.784 44.013 C 63.986 43.883 69.882 49.62 70.016 56.744 C 70.153 63.968 64.46 69.862 57.292 70.008 C 50.033 70.156 44.13 64.41 44.02 57.216 C 43.909 49.987 49.645 44.154 56.784 44.013 Z M 57.753 55.816 C 57.734 55.804 57.718 55.795 57.7 55.784 C 57.7 55.615 57.705 55.449 57.7 55.28 C 57.691 54.942 57.554 54.806 57.214 54.803 C 56.622 54.799 56.029 54.799 55.436 54.803 C 55.087 54.806 54.946 54.952 54.946 55.305 L 54.946 63.024 C 54.946 63.368 55.096 63.512 55.447 63.512 C 55.997 63.514 56.549 63.512 57.098 63.512 C 57.575 63.512 57.686 63.402 57.686 62.935 C 57.686 61.64 57.682 60.344 57.686 59.049 C 57.686 58.568 57.794 58.108 58.049 57.693 C 58.38 57.152 58.883 56.979 59.488 57.059 C 60.037 57.129 60.386 57.462 60.516 57.98 C 60.614 58.37 60.659 58.78 60.664 59.182 C 60.682 60.458 60.669 61.738 60.669 63.015 C 60.669 63.368 60.808 63.507 61.159 63.51 C 61.761 63.512 62.36 63.51 62.962 63.51 C 63.343 63.51 63.475 63.375 63.475 62.985 C 63.475 61.562 63.489 60.142 63.466 58.719 C 63.457 58.18 63.409 57.635 63.306 57.106 C 63.085 55.975 62.508 55.113 61.33 54.797 C 60.614 54.605 59.889 54.619 59.171 54.806 C 58.576 54.961 58.108 55.307 57.75 55.809 Z M 50.967 59.145 L 50.967 62.928 C 50.967 63.368 51.106 63.512 51.537 63.512 L 53.163 63.512 C 53.557 63.512 53.712 63.354 53.712 62.953 L 53.712 55.36 C 53.712 54.961 53.56 54.803 53.163 54.801 C 52.629 54.797 52.096 54.801 51.562 54.801 C 51.104 54.801 50.97 54.936 50.97 55.387 L 50.97 59.145 Z M 50.564 52.286 C 50.564 53.269 51.357 54.065 52.333 54.062 C 53.309 54.062 54.109 53.262 54.111 52.286 C 54.116 51.317 53.309 50.51 52.335 50.51 C 51.355 50.51 50.564 51.301 50.564 52.284 Z" fill="rgb(255, 255, 255)"></path></svg>',
                                    svgContentId: 11031440785
                                }
                            }, baseVariant, gestureVariant)
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-YOy7n.framer-1cn04ox, .framer-YOy7n .framer-1cn04ox { display: block; }", ".framer-YOy7n.framer-1cnw714 { cursor: pointer; height: 33px; overflow: visible; position: relative; text-decoration: none; width: 33px; }", ".framer-YOy7n .framer-1avy8l0 { flex: none; height: 115px; left: calc(49.56521739130437% - 115px / 2); position: absolute; top: calc(49.56521739130437% - 115px / 2); width: 115px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 33
 * @framerIntrinsicWidth 33
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"J7X9xTb5r":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"WqPBLyoyk":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerDK77DvEEr = withCSS(Component, css, "framer-YOy7n");
export default FramerDK77DvEEr;
FramerDK77DvEEr.displayName = "Linkedin";
FramerDK77DvEEr.defaultProps = {
    height: 33,
    width: 33
};
addPropertyControls(FramerDK77DvEEr, {
    WqPBLyoyk: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerDK77DvEEr, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerDK77DvEEr",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"J7X9xTb5r\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "33",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "33",
                "framerVariables": "{\"WqPBLyoyk\":\"link\"}",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./DK77DvEEr.map