// Generated by Framer (9a43cf4)
export default function metadata(params, activeLocale) {
    return {
        description: "A Full Stack Developer ,intregrating AI solutions to real life problems ",
        favicon: "https://framerusercontent.com/assets/fXC6nT0R4mVjA8e1Nuhvhgzl0.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/SjrHvw5tDivhbYp8TkRZlJm40.png",
        title: "DEVRAJ~PORTFOLIO"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}