// Generated by Framer (a4439fa)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
const cycleOrder = ["tctlCBhEE", "qdcaT7Xo0", "cPOTBL2WP", "aE2GdjvhY"];
const serializationHash = "framer-UMDk0";
const variantClassNames = {
    aE2GdjvhY: "framer-v-12dy0yf",
    cPOTBL2WP: "framer-v-1bovqjy",
    qdcaT7Xo0: "framer-v-1jo2y8w",
    tctlCBhEE: "framer-v-bmt1tj"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants === null || variants === void 0 ? void 0 : variants.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    duration: 0,
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value !== null && value !== void 0 ? value : config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
    "1": "tctlCBhEE",
    "2": "qdcaT7Xo0",
    "3": "cPOTBL2WP",
    "4": "aE2GdjvhY"
};
const getProps = ({
    height,
    id,
    label1,
    label2,
    label3,
    label4,
    width,
    ...props
}) => {
    var _ref, _ref1, _ref2, _humanReadableVariantMap_props_variant, _ref3, _ref4;
    return { ...props,
        HvfJHbU33: (_ref = label2 !== null && label2 !== void 0 ? label2 : props.HvfJHbU33) !== null && _ref !== void 0 ? _ref : "About",
        pwuah1x3V: (_ref1 = label3 !== null && label3 !== void 0 ? label3 : props.pwuah1x3V) !== null && _ref1 !== void 0 ? _ref1 : "Journal",
        s8uq9o_PT: (_ref2 = label4 !== null && label4 !== void 0 ? label4 : props.s8uq9o_PT) !== null && _ref2 !== void 0 ? _ref2 : "Updates",
        variant: (_ref3 = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref3 !== void 0 ? _ref3 : "tctlCBhEE",
        Zb96rmzbq: (_ref4 = label1 !== null && label1 !== void 0 ? label1 : props.Zb96rmzbq) !== null && _ref4 !== void 0 ? _ref4 : "Shop"
    };
};
const createLayoutDependency = (props, variants) => variants.join("-") + props.layoutDependency;
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        Zb96rmzbq,
        HvfJHbU33,
        pwuah1x3V,
        s8uq9o_PT,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        gestureVariant,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "tctlCBhEE",
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const sharedStyleClassNames = [];
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    className: cx(serializationHash, ...sharedStyleClassNames, "framer-bmt1tj", className, classNames),
                    "data-framer-name": "1",
                    layoutDependency: layoutDependency,
                    layoutId: "tctlCBhEE",
                    onHoverEnd: () => setGestureState({
                        isHovered: false
                    }),
                    onHoverStart: () => setGestureState({
                        isHovered: true
                    }),
                    onTap: () => setGestureState({
                        isPressed: false
                    }),
                    onTapCancel: () => setGestureState({
                        isPressed: false
                    }),
                    onTapStart: () => setGestureState({
                        isPressed: true
                    }),
                    ref: ref !== null && ref !== void 0 ? ref : ref1,
                    style: {
                        backgroundColor: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 100,
                        borderBottomRightRadius: 100,
                        borderTopLeftRadius: 100,
                        borderTopRightRadius: 100,
                        ...style
                    },
                    ...addPropertyOverrides({
                        aE2GdjvhY: {
                            "data-framer-name": "4"
                        },
                        cPOTBL2WP: {
                            "data-framer-name": "3"
                        },
                        qdcaT7Xo0: {
                            "data-framer-name": "2"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7S29kZSBNb25vLTUwMA==",
                                    "--framer-font-family": '"Kode Mono", monospace',
                                    "--framer-font-size": "14px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "0.1em",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)))"
                                },
                                children: "01"
                            })
                        }),
                        className: "framer-1ayl9te",
                        fonts: ["GF;Kode Mono-500"],
                        layoutDependency: layoutDependency,
                        layoutId: "ZW4ZYUR7z",
                        style: {
                            "--extracted-r6o4lv": "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            aE2GdjvhY: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7S29kZSBNb25vLTUwMA==",
                                            "--framer-font-family": '"Kode Mono", monospace',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-letter-spacing": "0.1em",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)))"
                                        },
                                        children: "04"
                                    })
                                })
                            },
                            cPOTBL2WP: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7S29kZSBNb25vLTUwMA==",
                                            "--framer-font-family": '"Kode Mono", monospace',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-letter-spacing": "0.1em",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)))"
                                        },
                                        children: "03"
                                    })
                                })
                            },
                            qdcaT7Xo0: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "R0Y7S29kZSBNb25vLTUwMA==",
                                            "--framer-font-family": '"Kode Mono", monospace',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "500",
                                            "--framer-letter-spacing": "0.1em",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)))"
                                        },
                                        children: "02"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "R0Y7SW50ZXItNTAw",
                                    "--framer-font-family": '"Inter", "Inter Placeholder", sans-serif',
                                    "--framer-font-size": "14px",
                                    "--framer-font-weight": "500",
                                    "--framer-letter-spacing": "-0.01em",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)))"
                                },
                                children: "Shop"
                            })
                        }),
                        className: "framer-1txck09",
                        "data-framer-name": "text",
                        fonts: ["GF;Inter-500"],
                        layoutDependency: layoutDependency,
                        layoutId: "JUO5E5m0u",
                        style: {
                            "--extracted-r6o4lv": "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: Zb96rmzbq,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            aE2GdjvhY: {
                                text: s8uq9o_PT
                            },
                            cPOTBL2WP: {
                                text: pwuah1x3V
                            },
                            qdcaT7Xo0: {
                                text: HvfJHbU33
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-UMDk0.framer-65g8ma, .framer-UMDk0 .framer-65g8ma { display: block; }", ".framer-UMDk0.framer-bmt1tj { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 36px; justify-content: center; overflow: hidden; padding: 14px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-UMDk0 .framer-1ayl9te, .framer-UMDk0 .framer-1txck09 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-UMDk0.framer-bmt1tj { gap: 0px; } .framer-UMDk0.framer-bmt1tj > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-UMDk0.framer-bmt1tj > :first-child { margin-left: 0px; } .framer-UMDk0.framer-bmt1tj > :last-child { margin-right: 0px; } }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 36
 * @framerIntrinsicWidth 91.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"qdcaT7Xo0":{"layout":["auto","fixed"]},"cPOTBL2WP":{"layout":["auto","fixed"]},"aE2GdjvhY":{"layout":["auto","fixed"]}}}
 * @framerVariables {"Zb96rmzbq":"label1","HvfJHbU33":"label2","pwuah1x3V":"label3","s8uq9o_PT":"label4"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerMBVArJ8Xg = withCSS(Component, css, "framer-UMDk0");
export default FramerMBVArJ8Xg;
FramerMBVArJ8Xg.displayName = "Pill";
FramerMBVArJ8Xg.defaultProps = {
    height: 36,
    width: 91.5
};
addPropertyControls(FramerMBVArJ8Xg, {
    variant: {
        options: ["tctlCBhEE", "qdcaT7Xo0", "cPOTBL2WP", "aE2GdjvhY"],
        optionTitles: ["1", "2", "3", "4"],
        title: "Variant",
        type: ControlType.Enum
    },
    Zb96rmzbq: {
        defaultValue: "Shop",
        displayTextArea: false,
        title: "Label 1",
        type: ControlType.String
    },
    HvfJHbU33: {
        defaultValue: "About",
        displayTextArea: false,
        title: "Label 2",
        type: ControlType.String
    },
    pwuah1x3V: {
        defaultValue: "Journal",
        displayTextArea: false,
        title: "Label 3",
        type: ControlType.String
    },
    s8uq9o_PT: {
        defaultValue: "Updates",
        displayTextArea: false,
        title: "Label 4",
        type: ControlType.String
    }
});
addFonts(FramerMBVArJ8Xg, [{
    explicitInter: true,
    fonts: [{
        family: "Kode Mono",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/kodemono/v1/A2BLn5pb0QgtVEPFnlYkkaoBgw4qv9odq6uy9D-TaOW2A3k.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZ1rib2Bg-4.woff2",
        weight: "500"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerMBVArJ8Xg",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "36",
                "framerIntrinsicWidth": "91.5",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"qdcaT7Xo0\":{\"layout\":[\"auto\",\"fixed\"]},\"cPOTBL2WP\":{\"layout\":[\"auto\",\"fixed\"]},\"aE2GdjvhY\":{\"layout\":[\"auto\",\"fixed\"]}}}",
                "framerVariables": "{\"Zb96rmzbq\":\"label1\",\"HvfJHbU33\":\"label2\",\"pwuah1x3V\":\"label3\",\"s8uq9o_PT\":\"label4\"}",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./MBVArJ8Xg.map